steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - gtfs-trip-update
      - --region=us-east1
      - --source=./TripUpdate
      - --trigger-http
      - --runtime=dotnet3
options:
  logging: CLOUD_LOGGING_ONLY
